{
	"version": 1615112111,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/sket-sheet0.png",
		"images/tanah-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/kursi_l-sheet0.png",
		"images/meja_l-sheet0.png",
		"images/ground-sheet0.png",
		"images/oppa-sheet0.png",
		"images/platform-sheet0.png",
		"images/box-sheet0.png",
		"images/sprite-sheet0.png",
		"images/flag-sheet0.png",
		"images/ground_bendera-sheet0.png",
		"images/climb_objek-sheet0.png",
		"images/serok_r-sheet0.png",
		"images/serok_r-sheet1.png",
		"images/crybaby-sheet0.png",
		"images/spawner-sheet0.png",
		"images/mob-sheet0.png",
		"images/namebox-sheet0.png",
		"images/namebox_centang-sheet0.png",
		"images/namebox_centang-sheet1.png",
		"images/lobby-sheet0.png",
		"images/karakter-sheet0.png",
		"images/bgm-sheet0.png",
		"images/ready-sheet0.png",
		"images/time_place-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/item-sheet0.png",
		"images/skill-sheet0.png",
		"images/skill_time.png",
		"images/titlepeta-sheet0.png",
		"images/bg-sheet0.png",
		"images/mulai-sheet0.png",
		"images/logotim-sheet0.png",
		"images/judul-sheet0.png",
		"images/credits-sheet0.png",
		"images/credits-sheet1.png",
		"images/item_fly-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/logo_item-sheet0.png",
		"images/logo_item-sheet1.png",
		"images/logo_skill-sheet0.png",
		"images/logo_skill-sheet1.png",
		"images/logo_skill-sheet2.png",
		"images/logo_suit-sheet0.png",
		"images/logo_suit_lawan-sheet0.png",
		"images/logo_suit_lawan-sheet1.png",
		"images/logo_suit_mine-sheet0.png",
		"images/box_tutorial-sheet0.png",
		"images/pilih_karakter-sheet0.png",
		"images/pilih_karakter-sheet1.png",
		"images/popup_pilih_karakter-sheet0.png",
		"images/popup_pilih_karakter-sheet1.png",
		"images/popup_pilih_karakter-sheet2.png",
		"images/popup_pilih_karakter-sheet3.png",
		"images/tab_pandi-sheet0.png",
		"images/tab_ani-sheet0.png",
		"images/tab_aldy-sheet0.png",
		"images/tab_susi-sheet0.png",
		"images/bt_ok_pilih_karakter-sheet0.png",
		"images/bt_ok_pilih_karakter-sheet1.png",
		"images/aldi_pilih-sheet0.png",
		"images/susi_pilih-sheet0.png",
		"images/gilo_host-sheet0.png",
		"images/gilo_host-sheet1.png",
		"images/guru_host-sheet0.png",
		"images/skill_cengeng-sheet0.png",
		"images/skill_indigo-sheet0.png",
		"images/itemefffect_pisang-sheet0.png",
		"images/itemefffect_shield-sheet0.png",
		"images/gum-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/status_karakter-sheet0.png",
		"images/status_karakter-sheet1.png",
		"images/status_karakter-sheet2.png",
		"images/status_karakter-sheet3.png",
		"images/status_karakter-sheet4.png",
		"images/sprite8-sheet0.png",
		"images/menang-sheet0.png",
		"images/menang-sheet1.png",
		"images/time_bar-sheet0.png",
		"images/tutorial-sheet0.png",
		"images/tutorial-sheet1.png",
		"images/tutorial-sheet2.png",
		"images/tutorial-sheet3.png",
		"images/next-sheet0.png",
		"images/back-sheet0.png",
		"images/bgm_bar-sheet0.png",
		"images/up_time-sheet0.png",
		"images/down_time-sheet0.png",
		"images/dinding-sheet0.png",
		"images/kelereng-sheet0.png",
		"images/reconnect-sheet0.png",
		"images/kredit_box-sheet0.png",
		"images/sprite2-sheet0.png",
		"media/zapsplat_cartoon_lick_46214.ogg",
		"media/zapsplat_cartoon_plug_water_plug_in_or_remove_002_46216.ogg",
		"media/zapsplat_cartoon_plug_water_plug_in_or_remove_003_46217.ogg",
		"media/zapsplat_cartoon_pull_pop_46218.ogg",
		"media/sfx - ambiak item.ogg",
		"media/sfx - gunoan item.ogg",
		"media/sfx - jalan di selain tanah.ogg",
		"media/sfx - jalan di tanah.ogg",
		"media/sfx - jatuh.ogg",
		"media/sfx - klik tombol close.ogg",
		"media/sfx - klik.ogg",
		"media/sfx - lompek.ogg",
		"media/sfx - mouse over.ogg",
		"media/sfx - skill ani kalau kanai.ogg",
		"media/sfx - skill hacker.ogg",
		"media/sfx - skill oppa.ogg",
		"media/you lose.ogg",
		"media/you win.ogg",
		"media/bgm intro.ogg",
		"media/bgm -  shakuji park.ogg",
		"media/bgm - happy dreamer .ogg",
		"media/bgm - magic cooking.ogg",
		"media/bgm - pops up the mind wings.ogg",
		"media/bgm - rat party.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"mobil.scon",
		"oppa.scon",
		"ani.scon",
		"aldi.scon",
		"susi.scon",
		"guru.scon",
		"item.scon",
		"c2mp-net.js",
		"c2mp-peer.js",
		"c2mp.js",
		"waker.js"
	]
}